import { City, User } from "../../types/userType";

export const users: User[] = [
  {
    id: "1",
    firstName: "דויד",
    lastName: "לוי",
    phoneNumber: "123-456-7890",
    address: "123 Main St",
    city: City.TLV,
    userType: "family",
    profilePicture:
      "https://res.cloudinary.com/globes/image/upload/t_desktop_article_content_header_800%2A392/v1660236836/direct/shutterstock_1563541219_lw0wnv.jpg",
    isApproved: false,
    approvedBy: "",
    approvedAt: new Date(0),
    createdAt: new Date(),
    email: "yuval047@gmail.com",
    vehicle: "פרטי",
  },
  {
    id: "2",
    firstName: "שרה",
    lastName: "כהן",
    phoneNumber: "987-654-3210",
    address: "456 Elm St",
    city: City.Jerusalem,
    userType: "volunteer",
    profilePicture:
      "https://res.cloudinary.com/globes/image/upload/t_desktop_article_content_header_800%2A392/v1660236836/direct/shutterstock_1563541219_lw0wnv.jpg",
    isApproved: false,
    approvedBy: "",
    approvedAt: new Date(0),
    createdAt: new Date(),
    email: "yuval047@gmail.com",
    vehicle: "פרטי",
  },
  {
    id: "3",
    firstName: "מיכאל",
    lastName: "רוזנברג",
    phoneNumber: "555-666-7777",
    address: "789 Oak St",
    city: City.Haifa,
    userType: "admin",
    profilePicture:
      "https://res.cloudinary.com/globes/image/upload/t_desktop_article_content_header_800%2A392/v1660236836/direct/shutterstock_1563541219_lw0wnv.jpg",
    isApproved: false,
    approvedBy: "",
    approvedAt: new Date(0),
    createdAt: new Date(),
    email: "yuval047@gmail.com",
    vehicle: "פרטי",
  },
  {
    id: "4",
    firstName: "רחל",
    lastName: "גולדמן",
    phoneNumber: "222-333-4444",
    address: "159 Pine St",
    city: City.PetahTikva,
    userType: "family",
    profilePicture:
      "https://res.cloudinary.com/globes/image/upload/t_desktop_article_content_header_800%2A392/v1660236836/direct/shutterstock_1563541219_lw0wnv.jpg",
    isApproved: true,
    approvedBy: "5",
    approvedAt: new Date(),
    createdAt: new Date(),
    email: "yuval047@gmail.com",
    vehicle: "פרטי",
  },
  {
    id: "6",
    firstName: "ישראל",
    lastName: "ישראלי",
    phoneNumber: "111-222-3333",
    address: "753 Maple St",
    city: City.Ashdod,
    userType: "volunteer",
    profilePicture:
      "https://res.cloudinary.com/globes/image/upload/t_desktop_article_content_header_800%2A392/v1660236836/direct/shutterstock_1563541219_lw0wnv.jpg",
    isApproved: true,
    approvedBy: "4",
    approvedAt: new Date(),
    createdAt: new Date(),
    email: "yuval047@gmail.com",
    vehicle: "פרטי",
  },
  {
    id: "7",
    firstName: "רחל",
    lastName: "גולדמן",
    phoneNumber: "222-333-4444",
    address: "159 Pine St",
    city: City.BatYam,
    userType: "family",
    profilePicture:
      "https://res.cloudinary.com/globes/image/upload/t_desktop_article_content_header_800%2A392/v1660236836/direct/shutterstock_1563541219_lw0wnv.jpg",
    isApproved: true,
    approvedBy: "5",
    approvedAt: new Date(),
    createdAt: new Date(),
    email: "yuval047@gmail.com",
    vehicle: "פרטי",
  },
  {
    id: "8",
    firstName: "רחל",
    lastName: "גולדמן",
    phoneNumber: "222-333-4444",
    address: "159 Pine St",
    city: City.PetahTikva,
    userType: "family",
    profilePicture:
      "https://res.cloudinary.com/globes/image/upload/t_desktop_article_content_header_800%2A392/v1660236836/direct/shutterstock_1563541219_lw0wnv.jpg",
    isApproved: true,
    approvedBy: "5",
    approvedAt: new Date(),
    createdAt: new Date(),
    email: "yuval047@gmail.com",
    vehicle: "פרטי",
  },
  {
    id: "9",
    firstName: "רחל",
    lastName: "גולדמן",
    phoneNumber: "222-333-4444",
    address: "159 Pine St",
    city: City.PetahTikva,
    userType: "family",
    profilePicture:
      "https://res.cloudinary.com/globes/image/upload/t_desktop_article_content_header_800%2A392/v1660236836/direct/shutterstock_1563541219_lw0wnv.jpg",
    isApproved: true,
    approvedBy: "5",
    approvedAt: new Date(),
    createdAt: new Date(),
    email: "yuval047@gmail.com",
    vehicle: "פרטי",
  },
  {
    id: "10",
    firstName: "רחל",
    lastName: "גולדמן",
    phoneNumber: "222-333-4444",
    address: "159 Pine St",
    city: City.PetahTikva,
    userType: "family",
    profilePicture:
      "https://res.cloudinary.com/globes/image/upload/t_desktop_article_content_header_800%2A392/v1660236836/direct/shutterstock_1563541219_lw0wnv.jpg",
    isApproved: true,
    approvedBy: "5",
    approvedAt: new Date(),
    createdAt: new Date(),
    email: "yuval047@gmail.com",
    vehicle: "פרטי",
  },
  {
    id: "11",
    firstName: "רחל",
    lastName: "גולדמן",
    phoneNumber: "222-333-4444",
    address: "159 Pine St",
    city: City.PetahTikva,
    userType: "family",
    profilePicture:
      "https://res.cloudinary.com/globes/image/upload/t_desktop_article_content_header_800%2A392/v1660236836/direct/shutterstock_1563541219_lw0wnv.jpg",
    isApproved: true,
    approvedBy: "5",
    approvedAt: new Date(),
    createdAt: new Date(),
    email: "yuval047@gmail.com",
    vehicle: "פרטי",
  },
];
