name: CI/CD for Frontend

on:
  push:
    branches:
      - workflow-front

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: |
          npm install

      - name: Run tests
        run: |
          npm test

      - name: Build Docker image
        run: |
          docker build -t my-frontend:latest ./frontend

      - name: Push Docker image to Docker Hub
        run: |
          echo Aa123456! | docker login -u yadtamar --password-stdin
          docker tag my-frontend:latest yadtamar/front:latest
          docker push yadtamar/front:latest
